### ISSUE TITLE
postbin proxy

### ISSUE THREAD

**Issue by progrium** [Runscope/requestbin#3]
In order to migrate usage from PostBin to RequestBin, and to avoid quota limits (and ridiculous operational costs), a new project should be started to run on Heroku that postbin.org can be pointed at. It will assume incoming paths are actual PostBins, it will create a RequestBin for it, and keep a map in memory. All future requests will be proxied to RequestBin. Browser requests to PostBin will be redirected to RequestBin and the appropriate bin mapping. 

Once the RequestBin expires for a PostBin, the proxy will start returning 404.

**Comment by lonnen** [comment]
Postbin redirects to RequestBin now. I believe this issue can be resolved.
