### ISSUE TITLE
HTTPS: Insecure Content

### ISSUE THREAD

**Issue by dahlbyk** [Runscope/requestbin#33]
https://requestb.in/ gives an insecure content warning about http://ads.perfectaudience.com; over https, that host has a certificate mismatch. Why are ad services so bad at this. 😠

Other HTTPS notes:

- A RequestBin created over `https` lands on an `https` page that shows `http` throughout the page.
- I'd love to see the home page and all new Bins forced to `https`.

**Comment by johnsheehan** [comment]
The mismatch was our bad (we didn't support TLS on the live site for a long time and the pixel URL was hardcoded). I've removed that reference.

https is now forced for all requests and displayed properly on the bin page. Let me know if you see something else.

**Comment by dahlbyk** [comment]
Looks great, thanks!
