### ISSUE TITLE
requestb.in down?

### ISSUE THREAD

**Issue by vdespa** [Runscope/requestbin#41]
Hi and apologize if this is not the right place to ask this.

It seems that requestb.in is down. I am getting the error: 

Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details.

Is this still maintained? Thanks for your work.

**Comment by johnsheehan** [comment]
The site is frequently flooded with traffic (intentionally or not, who knows), which can cause unavailability.  You can self host your own instance on Heroku for free. Instructions int he readme.
